name: ✅ Vérification JSON

permissions:
  contents: read

on:
  push:
    paths:
      - 'data/**/*.json'
  pull_request:
    paths:
      - 'data/**/*.json'

jobs:
  validate-json:
    name: Valider tous les fichiers JSON dans /data
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Cloner le repo
        uses: actions/checkout@v3

      - name: 🧪 Valider tous les fichiers JSON dans /data
        run: |
          echo "🔍 Vérification des fichiers JSON dans /data..."
          for file in data/*.json; do
            echo "✅ Vérification de $file..."
            python -m json.tool "$file" > /dev/null || {
              echo "❌ Erreur dans $file"
              exit 1
            }

          done